### ISSUE TITLE
Error: found in requirements.yaml, but missing in charts/ directory: common

### ISSUE THREAD

**Issue by jpveritone** [cloudposse/prometheus-to-cloudwatch#10]
Trying to install via helm ```cd chart
helm install .``` I get `Error: found in requirements.yaml, but missing in charts/ directory: common`.
I added to my repo via `helm repo add common https://kubernetes-charts-incubator.storage.googleapis.com/` but made no difference. Next try route of just downloading https://kubernetes-charts-incubator.storage.googleapis.com/common-0.0.4.tgz and installing but that gives me `Error: release kind-saola failed: no objects visited`. I prefer not to go down this path of installing one dependency at a time. Any clues on how to resolve the original error?

**Comment by osterman** [comment]
Hrm... yes, my guess is things broke maybe after charts moved back to helm org. Also, `common` was an experimental chart library of sorts. We've gone a slightly different route, one that we actively maintain: https://github.com/cloudposse/charts/blob/master/incubator/monochart/

If you look at `values.example.yaml` you can see how to use this chart to deploy all common kinds of apps. It would be quite easy to use that chart in place of this one. The monochart is one chart to rule them all so we can present a simple declarative interface for deploying apps on kubernetes.

Join us on slack: https://slack.cloudposse.com and we can help you get that up and running.

**Comment by ryanjfrizzell** [comment]
just in case you're still stuck 
```
git clone https://github.com/cloudposse/prometheus-to-cloudwatch.git
cd chart
helm repo add common https://kubernetes-charts-incubator.storage.googleapis.com/
helm dependency update
helm install .
```

**Comment by jpveritone** [comment]
Closing issue since not deploying to k8s any longer
