### ISSUE TITLE
Ability to set Dimensions per Metric

### ISSUE THREAD

**Issue by austince** [cloudposse/prometheus-to-cloudwatch#27]
Hey there, would anyone be interested in a PR that allows you to set the dimensions on a per-metric, or perhaps per-metric-glob, basis? We're running into the issue of the 10 metric limit truncating the actual dimensions we care about. 

I'm thinking about updating the `Bridge` and passing in a flag like:

```go
	dimensionsForMetrics     = flag.String("dimensions_for_metrics", os.Getenv("DIMENSIONS_FOR_METRICS"), "Hard-coded dimensions for metrics (semi-colon-separated list of comma-separated dimensions, e.g. 'flink_jobmanager=job,host;zk_up=host,pod;')")

// ...

type Bridge struct {
	dimensionsForMetricMap        map[string][]string
        // or
	dimensionsForMetrics        []glob.Glob[]string
}
```

Or even the ability to set the max # of dimensions per metric might solve our use case.

**Comment by aknysh** [comment]
@austince  PRs are very welcome, thanks

**Comment by austince** [comment]
@ankysh any suggestions on the feature / approach?

**Comment by austince** [comment]
Also, has there been any discussion for moving to go modules?
