### ISSUE TITLE
RabbitMQ prometheus endpoint return status code 406

### ISSUE THREAD

**Issue by rjbaucells** [cloudposse/prometheus-to-cloudwatch#30]
Current implementation performs HTTP request with `Accept` header including `quality factor` (`q` parameter) and extensions (see [code](https://github.com/cloudposse/prometheus-to-cloudwatch/blob/69a11e0656e36587421c98b7d9b87d4df5ebb044/prometheus_to_cloudwatch.go#L34)).

RabbitMQ prometheus endpoint returns HTTP status code `406 Not Acceptable` (see [RabbitMQ issue](https://github.com/rabbitmq/rabbitmq-prometheus/issues/13)) with current `Accept` header. The problem is related to the `version=0.0.4` extension of the `text/plain` media type, removing the `version=0.0.4` from the header value resolves the issue.

Is there any specific reason to have the `version=0.0.4` extension specified for the `text/plain` media type?

Would it be acceptable to have it removed? (I can provide PR)

Thanks,

RJB

**Comment by lukebakken** [comment]
FWIW this is already fixed in RabbitMQ via [this commit](https://github.com/rabbitmq/rabbitmq-prometheus/commit/d639c807d4b7767bfe28e78d9e89b4560160b829).

**Comment by rjbaucells** [comment]
Yes, the issue can be closed
