### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by jicowan** [cloudposse/prometheus-to-cloudwatch#8]
The image or image tag in the values file cannot be pulled.

**Comment by jicowan** [comment]
Updated the image tag to 0.1.2, but I'm not sure that is the version I should be using.  I am seeing the following errors in the container logs: 
```
2018/09/21 16:03:37 prometheus-to-cloudwatch: published 125 metrics to CloudWatch
2018/09/21 16:03:50 prometheus-to-cloudwatch: error publishing to CloudWatch: InvalidParameterValue: The value for parameter MetricData.member.9.Dimensions.member.1.Value contains non-ASCII characters.
The value for parameter MetricData.member.10.Dimensions.member.1.Value contains non-ASCII characters.
```
I do not see the custom metrics in CW yet.

**Comment by jicowan** [comment]
Was sending metrics to the wrong region.  Will close this issue.  Please update the values.yaml with the appropriate image tag.

**Comment by aknysh** [comment]
@jicowan 
sorry for a late response and thanks for testing the module!
you are correct, the latest release is https://github.com/cloudposse/prometheus-to-cloudwatch/releases/tag/0.1.2
we'll update the image as you suggested.
